import { Controller, Get, Param } from '@nestjs/common';

@Controller('station')
export class AppController {
  constructor() {}

  @Get()
  getHello(@Param('apikey') apikey: string) {
    console.log('In controller');
    return `[
      {
         "Id":"e7726826-7449-4550-aed5-495bed7d4bc7",
         "Name":"ТЕСТ 2",
         "Address":"ваываыва",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":33,
            "Lat":44
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"e2cadd8a-f3a1-4933-89e9-b05ea702c943",
         "Name":"Тест ЭлСи Калуга",
         "Address":"Тест ЭлСи Калуга",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":36.299835,
            "Lat":54.53242
         },
         "TakeOffBefore":"before",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"ddba5510-6d3b-4e33-8ec8-6a9ca85f4fa4",
         "Name":"GasStation TEST",
         "Address":"ТЕСТ",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":45.558333,
            "Lat":56.891122
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "1",
                  "2",
                  "3",
                  "5",
                  "12"
               ]
            },
            "2":{
               "Fuels":[
                  "13"
               ]
            },
            "5":{
               "Fuels":[
                  "1",
                  "2",
                  "3",
                  "5",
                  "12"
               ]
            },
            "6":{
               "Fuels":[
                  "12"
               ]
            },
            "7":{
               "Fuels":[
                  "1",
                  "2"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":52,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":51.8,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"3",
               "Price":23.23,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            },
            {
               "Id":"5",
               "Price":24.24,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"12",
               "Price":20.25,
               "Type":"Пропан",
               "TypeId":6,
               "Brand":null,
               "Name":"Пропан"
            },
            {
               "Id":"13",
               "Price":18.18,
               "Type":"Метан",
               "TypeId":7,
               "Brand":null,
               "Name":"Метан"
            }
         ]
      },
      {
         "Id":"6465547f-2d8f-4209-8202-e9c067b2ee4a",
         "Name":"ТЕСТ 3",
         "Address":"далвладлв",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":73,
            "Lat":88
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"2d8d915a-5bd6-41f0-acdb-6e2fa6bf20ba",
         "Name":"ЗВЕЗДА 1",
         "Address":"50 лет октября 99г",
         "Brand":"Звезда Тест",
         "BrandId":"15748f9d-3d8c-4f7b-8d93-d4e57679dddd",
         "Location":{
            "Lon":37.679398,
            "Lat":55.632278
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "12"
               ]
            },
            "2":{
               "Fuels":[
                  "12"
               ]
            },
            "4":{
               "Fuels":[
                  "1"
               ]
            },
            "5":{
               "Fuels":[
                  "12"
               ]
            },
            "6":{
               "Fuels":[
                  "1"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":41.2,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":46,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"5",
               "Price":40,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"12",
               "Price":19,
               "Type":"Пропан",
               "TypeId":6,
               "Brand":null,
               "Name":"Пропан"
            }
         ]
      },
      {
         "Id":"6cca7fa6-d650-4bb6-93bc-733fdfb2a4df",
         "Name":"АЗС-1",
         "Address":"Абакан ул. Дружбы Народов, 54",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":91.41606,
            "Lat":53.74633
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"aef1bbe9-5723-46f8-9200-b9d1c5710144",
         "Name":"АЗС-10",
         "Address":"Абакан ул. Стофато, 1A",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":91.40703,
            "Lat":53.69647
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"377fdf75-e45f-44ea-8e81-8cf81b23cabc",
         "Name":"АЗС №22",
         "Address":"Томск, 2-я Тестовая улица, 22",
         "Brand":"ТЕСТ СИБНЕФТЕКАРТ",
         "BrandId":"6ee2633d-f39d-4495-abc5-d858b702b53d",
         "Location":{
            "Lon":84.990549,
            "Lat":56.442566
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":[
            {
               "Id":"6",
               "Price":50.5,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТЗ"
            },
            {
               "Id":"1",
               "Price":44.5,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"4",
               "Price":56,
               "Type":"100",
               "TypeId":4,
               "Brand":null,
               "Name":"100"
            },
            {
               "Id":"2",
               "Price":47,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"11",
               "Price":55.5,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ+"
            },
            {
               "Id":"3",
               "Price":53.4,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            }
         ]
      },
      {
         "Id":"09bcf175-1a66-4f82-9c80-51879ce899e9",
         "Name":"тест6",
         "Address":"Там-то там-то",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":50,
            "Lat":50
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"e16eb245-e7b4-46ea-a638-f5b2ef99407e",
         "Name":"АЗС+ ТЕСТ 1",
         "Address":"50 лет октября 94г",
         "Brand":"АЗС+ ТЕСТ",
         "BrandId":"6a4788d6-836c-4e50-bf33-8dd5747e5bf9",
         "Location":{
            "Lon":37.679398,
            "Lat":55.688645
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "7",
                  "8"
               ]
            },
            "2":{
               "Fuels":[
                  "7"
               ]
            },
            "3":{
               "Fuels":[
                  "7",
                  "8"
               ]
            },
            "4":{
               "Fuels":[
                  "7"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":35,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":35,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"8",
               "Price":43.56,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95+"
            },
            {
               "Id":"5",
               "Price":42.7,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"7",
               "Price":42.6,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92+"
            },
            {
               "Id":"11",
               "Price":43.9,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ+"
            }
         ]
      },
      {
         "Id":"7bb9e2d9-d5d0-4ac6-8dac-c6d86444ea44",
         "Name":"Топаз tv2",
         "Address":"50 лет октября 94г",
         "Brand":"ТЕСТ Топаз (tv2)",
         "BrandId":"2fde1075-219f-4a9b-a11c-1ec6e18361dc",
         "Location":{
            "Lon":37.679398,
            "Lat":18.95208
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":null,
         "Fuels":null
      },
      {
         "Id":"e8cf27bd-3304-4f25-9a5c-7ff221491eab",
         "Name":"ТестКомп ТестАЗС 454 Кисельня прав. сторона",
         "Address":"ЛО, Волховский р-н, д. Кисельня, ул. Центральная, д. 13/2",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":32.130573,
            "Lat":60.004947
         },
         "TakeOffBefore":"after",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "1"
               ]
            },
            "2":{
               "Fuels":[
                  "1",
                  "5"
               ]
            },
            "3":{
               "Fuels":[
                  "1",
                  "2"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":29,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":30,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"3",
               "Price":40,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            },
            {
               "Id":"5",
               "Price":50,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"12",
               "Price":28.8,
               "Type":"Пропан",
               "TypeId":6,
               "Brand":null,
               "Name":"Пропан"
            }
         ]
      },
      {
         "Id":"bda08def-95a3-4f03-8d00-51cab7a2f20f",
         "Name":"АЗС2 Тестовая",
         "Address":"г.Томск",
         "Brand":"ТЕСТ СИБНЕФТЕКАРТ",
         "BrandId":"6ee2633d-f39d-4495-abc5-d858b702b53d",
         "Location":{
            "Lon":84.953234,
            "Lat":56.484445
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "1",
                  "2",
                  "3"
               ]
            },
            "2":{
               "Fuels":[
                  "1",
                  "6"
               ]
            },
            "3":{
               "Fuels":[
                  "1",
                  "2",
                  "3",
                  "6",
                  "14"
               ]
            },
            "4":{
               "Fuels":[
                  "2"
               ]
            },
            "5":{
               "Fuels":[
                  "2"
               ]
            },
            "6":{
               "Fuels":[
                  "1",
                  "2"
               ]
            },
            "7":{
               "Fuels":[
                  "12"
               ]
            },
            "8":{
               "Fuels":[
                  "6"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"14",
               "Price":33,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"80"
            },
            {
               "Id":"6",
               "Price":37,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТЗ"
            },
            {
               "Id":"1",
               "Price":40,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":45,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"3",
               "Price":47,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            },
            {
               "Id":"12",
               "Price":30,
               "Type":"Пропан",
               "TypeId":6,
               "Brand":null,
               "Name":"Пропан"
            }
         ]
      },
      {
         "Id":"2965ba3f-efa4-404c-a1a1-132e7dac46e6",
         "Name":"Тест 2",
         "Address":"Адрес",
         "Brand":"Тест 2",
         "BrandId":"81073722-08de-42f2-9129-8d9f271a0ea0",
         "Location":{
            "Lon":37.389167,
            "Lat":55.835275
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "2":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "3":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "4":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "5":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "6":{
               "Fuels":[
                  "11"
               ]
            },
            "7":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "8":{
               "Fuels":[
                  "1",
                  "2",
                  "5",
                  "8",
                  "11"
               ]
            },
            "9":{
               "Fuels":[
                  "12",
                  "13"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"3",
               "Price":47.8,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            },
            {
               "Id":"1",
               "Price":41.7,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":45.6,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"11",
               "Price":46.2,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ+"
            },
            {
               "Id":"5",
               "Price":45.2,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"12",
               "Price":22.3,
               "Type":"Пропан",
               "TypeId":6,
               "Brand":null,
               "Name":"Пропан"
            },
            {
               "Id":"13",
               "Price":14.1,
               "Type":"Метан",
               "TypeId":7,
               "Brand":null,
               "Name":"Метан"
            },
            {
               "Id":"8",
               "Price":46.6,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95+"
            }
         ]
      },
      {
         "Id":"6e414591-ac6a-4103-928d-e3add1c8781c",
         "Name":"Тест 1",
         "Address":"Адрес",
         "Brand":"Тест 1",
         "BrandId":"a9e6069c-f050-43ec-ad50-85413a9c6ac1",
         "Location":{
            "Lon":37.546031,
            "Lat":55.900824
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "2":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "3":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "4":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "5":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "6":{
               "Fuels":[
                  "11"
               ]
            },
            "7":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            },
            "8":{
               "Fuels":[
                  "2",
                  "3",
                  "5",
                  "8",
                  "11"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":41.7,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":45.6,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"3",
               "Price":47.8,
               "Type":"98",
               "TypeId":3,
               "Brand":null,
               "Name":"98"
            },
            {
               "Id":"5",
               "Price":45.2,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"8",
               "Price":46.6,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"AI95"
            },
            {
               "Id":"11",
               "Price":46.2,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ+"
            },
            {
               "Id":"15",
               "Price":50.8,
               "Type":"АЭРО",
               "TypeId":null,
               "Brand":null,
               "Name":"95аэро"
            }
         ]
      },
      {
         "Id":"41ed38d1-47ee-4ad3-aca5-455ea296e218",
         "Name":"RusOil TEST",
         "Address":"Адрес",
         "Brand":null,
         "BrandId":null,
         "Location":{
            "Lon":38.968576,
            "Lat":45.049189
         },
         "TakeOffBefore":"both",
         "PostPay":false,
         "Enable":true,
         "Columns":{
            "1":{
               "Fuels":[
                  "1",
                  "2"
               ]
            },
            "2":{
               "Fuels":[
                  "1",
                  "2"
               ]
            },
            "3":{
               "Fuels":[
                  "5",
                  "11"
               ]
            },
            "4":{
               "Fuels":[
                  "5",
                  "11"
               ]
            }
         },
         "Fuels":[
            {
               "Id":"1",
               "Price":43.9,
               "Type":"92",
               "TypeId":1,
               "Brand":null,
               "Name":"92"
            },
            {
               "Id":"2",
               "Price":50.9,
               "Type":"95",
               "TypeId":2,
               "Brand":null,
               "Name":"95"
            },
            {
               "Id":"5",
               "Price":50.1,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ"
            },
            {
               "Id":"11",
               "Price":51.4,
               "Type":"ДТ",
               "TypeId":5,
               "Brand":null,
               "Name":"ДТ+"
            }
         ]
      }
   ]`;
  }
}
